Add section folding for empty sections
immortius/gw2-wardrobe-unlock pull request #7
Opened 2019-10-12 13:39 UTC by Blackgen

This is an idea I had. 
When sections are empty (all emlements are not hidden / unlocked) the section will be folded.

It can still be opened, but it will be folded again if the filter is changed & the section would be empty again.

I used jquery to determine if a section is empty, the query would be like this:
`$('#example-section .item:not(.hidden):not(.unlocked)').length == 0` -> section is beeing folded.

@immortius, what is your opinion on this? 
Do you think this is a useful feature?

2019-10-14 22:30 UTC, immortius requested changes
Overall looks good, just has one debug statement that should be removed before it is added.

2019-10-14 22:30 UTC, immortius commented on site/js/main.js
> +console.log("update ")
Remove this debug statement

2019-10-19 14:45 UTC, Blackgen commented
I've removed the log call

2019-10-22 11:47 UTC, merged

2019-10-22 11:47 UTC, immortius commented
Cheers!